practice/config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    get '/articles' => 'articles#index'
    get '/articles/new' => 'articles#new', :as => 'new_article'
    post '/articles' => 'articles#create', :as => 'create_article'
end

practice/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

practice/app/models/article.rb
class Article < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    validates :body, presence: true, length: { minimum: 10 }
end

practice/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

practice/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    layout 'double', only: [:new]
    
    def index
        @number = 20
        @articles = Article.all
    end

    def show; end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)

        if @article.save
            redirect_to articles_path
        else
            render :new
        end
    end

    def edit; end

    def update; end

    def delete; end

    private

    def article_params
        params.require(:article).permit(:name, :body)
    end
end

practice/app/helpers/application_helper.rb
module ApplicationHelper
end

practice/app/helpers/articles_helper.rb
module ArticlesHelper
end

practice/app/views/articles/_header.html.erb
Official Header

practice/app/views/articles/index.html.erb
<% arr = [1,2,3] %>
<%= arr[0] %>
<%= @number %>

<%= render "header" %>

<table>
    <thead>
        <tr>
            <th>Count</th>
            <th>ID</th>
            <th>Name</th>
            <th>Class</th>
            <th>Body</th>
        </tr>
    </thead>

    <tbody>
        <% ctr = 1 %> <% @articles.each do |article| %>
        <tr>
            <td><%= ctr %></td>
            <td><%= article.id %></td>
            <td><%= article.name %></td>
            <td><%= "Class: #{article.class}" %></td>
            <td><%= article.body %></td>
        </tr>
        <% ctr += 1 %> <% end %>
    </tbody>
</table>

<hr />

<%= @articles.inspect %>

<hr />

<br />

<%= link_to 'New Article', new_article_path %>

practice/app/views/articles/new.html.erb
<%= form_with scope:@article, url: create_article_path, local: true do |f| %>

<p>
    <% if @article.errors.any? %>
        <ul>
            <% @article.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <% end %>
</p>

<p>
    <%= f.label :name %>
    <br />
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :body %>
    <br />
    <%= f.text_field :body %>
</p>

<p><%= f.submit %></p>

<% end %>

practice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <marquee>header</marquee>
    <%= yield %>
    <marquee>footer</marquee>
  </body>
</html>

practice/app/views/layouts/double.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <marquee>header</marquee>
    <%= yield %>
    <marquee>footer</marquee>
  </body>
</html>