tutorial/config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    # root 'articles#index'

    # get '/articles', to: 'articles#index'
    # get '/articles/:id', to: 'articles#show'

    resources :articles do
        resources :comments
    end

    resources :categories
end

tutorial/app/models/article.rb
class Article < ApplicationRecord
    include Visible
    has_many :comments, dependent: :destroy

    validates :title, presence: true, uniqueness: true
    validates :body, presence: true, length: { minimum: 10 }
end

tutorial/app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, uniqueness: true
end

tutorial/app/models/comment.rb
class Comment < ApplicationRecord
    include Visible
    belongs_to :article
end

tutorial/app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern

    VALID_STATUSES = %w[public private archived]

    included { validates :status, inclusion: { in: VALID_STATUSES } }

    class_methods do
        def public_count
            where(status: 'public').count
        end
    end

    def archived?
        status == 'archived'
    end
end

tutorial/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    http_basic_authenticate_with name: 'dhh',
                                 password: 'secret',
                                 except: %i[index show]

    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def create
        # @article = Article.new(title: "...", body: "...")
        @article = Article.new(article_params)

        if @article.save
            redirect_to @article
        else
            render :new
        end
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])

        if @article.update(article_params)
            redirect_to @article
        else
            render :edit
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy

        redirect_to articles_path
    end

    private

    def article_params
        params.require(:article).permit(:title, :body, :status)
    end
end

tutorial/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all
    end

    def show
        @category = Category.find(params[:id])
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)

        if @category.save
            redirect_to @category
        else
            render :new
        end
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])

        if @category.update(category_params)
            redirect_to @category
        else
            render :edit
        end
    end

    def destroy
        @category = Category.find(params[:id])
        @category.destroy

        redirect_to categories_path(@categories)
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end
end

tutorial/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: 'dhh', password: 'secret', only: :destroy

    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end

    private

    def comment_params
        params.require(:comment).permit(:commenter, :body, :status)
    end
end

tutorial/app/helpers/categories_helper.rb
module CategoriesHelper
end

tutorial/app/helpers/comments_helper.rb
module CommentsHelper
end

tutorial/app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
<div>
    <%= form.label :title %><br />
    <%= form.text_field :title %> <%
    article.errors.full_messages_for(:title).each do |message| %>
    <div><%= message %></div>
    <% end %>
</div>

<div>
    <%= form.label :body %><br />
    <%= form.text_area :body %><br />
    <% article.errors.full_messages_for(:body).each do |message| %>
    <div><%= message %></div>
    <% end %>
</div>

<div>
    <%= form.label :status %><br />
    <%= form.select :status, ['public', 'private', 'archived'], selected:
    'public' %>
</div>

<br />

<div><%= form.submit %></div>

<% end %>

tutorial/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

<br />
<hr />
<br />

<button><%= link_to "Back", article_path %></button>

tutorial/app/views/articles/index.html.erb
<h1>Articles</h1>

<div>Our blog has <%= Article.public_count %> articles and counting!</div>

<br />

<% @articles.each do |article| %>
<!-- <a href="/articles/<%= article.id %>"> -->
<!-- <a href="<%= article_path(article) %>">
    <%= article.title %>
  </a> -->
<div><%= link_to article.title, article %></div>
<% end %>

<br />
<hr />
<br />

<button><%= link_to "New Article", new_article_path %></button>

tutorial/app/views/articles/new.html.erb
<h1>New Article</h1>

<!-- <%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <% @article.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %> -->

<%= render "form", article: @article %>

<br />
<hr />
<br />

<button><%= link_to "Back", articles_path %></button>

tutorial/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<button><%= link_to "Edit", edit_article_path(@article) %></button>

<br />
<br />

<button>
    <%= link_to "Destroy", article_path(@article), method: :delete, data: {
    confirm: "Are you sure?" } %>
</button>

<br />
<br />
<hr />
<br />

<button><%= link_to "Back", articles_path(@articles) %></button>

<br />
<br />
<hr />
<br />

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

tutorial/app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>
<div>
    <%= form.label :name %><br />
    <%= form.text_field :name %> <%
    category.errors.full_messages_for(:name).each do |message| %>
    <div><%= message %></div>
    <% end %>
</div>

<br />

<div><%= form.submit %></div>
<% end %>

<br />
<hr />
<br />

<%= link_to 'All Categories', categories_path(@categories) %>

tutorial/app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render "form", category: @category %>

tutorial/app/views/categories/index.html.erb
<h1>Categories</h1>

<ul>
    <% @categories.each do |category| %>
    <li><%= link_to category.name, category %></li>
    <% end %>
</ul>

<%= link_to "New Category", new_category_path %>

tutorial/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render "form", category: @category %>

tutorial/app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<%= link_to "Edit", edit_category_path(@category) %> <br /><br />

<%= link_to "Destroy", category_path(@category), method: :delete, data: {
confirm: "Are you sure?" } %>

<br />
<br />
<hr />
<br />

<%= link_to 'All Categories', categories_path(@categories) %>

tutorial/app/views/comments/_comment.html.erb
<p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
</p>

<p>
    <strong>Comment:</strong>
    <%= comment.body %>
</p>

<p>
    <%= link_to 'Destroy Comment', [comment.article, comment], method: :delete,
    data: { confirm: "Are you sure?" } %>
</p>

tutorial/app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
<p>
    <%= form.label :commenter %><br />
    <%= form.text_field :commenter %>
</p>
<p>
    <%= form.label :body %><br />
    <%= form.text_area :body %>
</p>

<div>
    <%= form.label :status %><br />
    <%= form.select :status, ['public', 'private', 'archived'], selected:
    'public' %>
</div>

<p><%= form.submit %></p>
<% end %>

tutorial/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutorial</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>